### ISSUE TITLE
"urlopen error" error when trying to upload a basic_info report

### ISSUE THREAD

**Issue by dkarchmer** [iotile/iotile_analytics#47]
Try
```
analytics-host --web-push-label test1 -u david@karchmer.com -w -c -t basic_info -a streams=True -o out b--0008-0000-0000-053a
```

and get

```
Rendered report to: out.txt                                                                                                                                                                           
Uploading report to iotile.cloud server
Traceback (most recent call last):                                                                                                                                                                    
  File "/Users/david/.virtualenv/analytics-runner/bin/analytics-host", line 11, in <module>
    sys.exit(cmdline_main())
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/scripts/analytics_host.py", line 425, in cmdline_main
    retval = main(argv)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/scripts/analytics_host.py", line 416, in main
    upload_report(args.domain, rendered_paths, label=args.web_push_label, group=group, slug=args.web_push_slug)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/scripts/analytics_host.py", line 180, in upload_report
    uploader.upload_report(label, files, group=group, slug=slug)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/reports/cloud_uploader.py", line 69, in upload_report
    urls, fields = self._get_signed_urls(report_id, keys)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/reports/cloud_uploader.py", line 125, in _get_signed_urls
    resp_list = self._session.post_multiple(urls, payloads, message="Getting file upload authorization", include_auth=True)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/core/session.py", line 277, in post_multiple
    raise failed[0]
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/core/session.py", line 388, in _generic_url_poster
    resp = urlopen(req)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 549, in _open
    'unknown_open', req)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: b'https>
```

**Comment by timburke** [comment]
I see the problem.  It came from the fix to this issue:
https://stackoverflow.com/questions/8705962/python-http-put-with-unencoded-binary-data/8715815#8715815

**Comment by timburke** [comment]
It looks like python 2 requires the url to be utf-8 encoded bytes (same as str on python 2) whereas python 3 requires it to a unicode string

**Comment by timburke** [comment]
I'll fix this and add some test coverage of post behavior on python 2 and 3
