### ISSUE TITLE
415 error: Unsupported Media Type

### ISSUE THREAD

**Issue by dkarchmer** [iotile/iotile_analytics#50]
Try
```
analytics-host -t stream_overview b--0008-0000-0000-053a -a stream=temp -c -o temperature -a units=Celsius -w --web-push-label=test1 -u david@karchmer.com
```

and get

```
Rendered report to: temperature.html                                                                                                                                                                  
Uploading report to iotile.cloud server
Traceback (most recent call last):                                                                                                                                                                    
  File "/Users/david/.virtualenv/analytics-runner/bin/analytics-host", line 11, in <module>
    sys.exit(cmdline_main())
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/scripts/analytics_host.py", line 425, in cmdline_main
    retval = main(argv)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/scripts/analytics_host.py", line 416, in main
    upload_report(args.domain, rendered_paths, label=args.web_push_label, group=group, slug=args.web_push_slug)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/scripts/analytics_host.py", line 180, in upload_report
    uploader.upload_report(label, files, group=group, slug=slug)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/reports/cloud_uploader.py", line 69, in upload_report
    urls, fields = self._get_signed_urls(report_id, keys)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/interactive/reports/cloud_uploader.py", line 125, in _get_signed_urls
    resp_list = self._session.post_multiple(urls, payloads, message="Getting file upload authorization", include_auth=True)
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/core/session.py", line 295, in post_multiple
    raise failed[0]
  File "/Users/david/.virtualenv/analytics-runner/lib/python3.6/site-packages/iotile_analytics/core/session.py", line 411, in _generic_url_poster
    resp = urlopen(req)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 415: Unsupported Media Type
```

Guessing is another Python3 encoding issue

**Comment by dkarchmer** [comment]
Need to do a little work to be able to test on my local server, at which time, I will be able to say what the server got

**Comment by dkarchmer** [comment]
On the development server, the error is a little different, but the problem likely the same.

When I print the `request.data` that I get (where you expect the payload), I get

```
{
     '{"name": "temperature.html", "acl": "private", "content_type": "text/html"}': ''
}
```

instead of

```
{"name": "temperature.html", "acl": "private", "content_type": "text/html"}
```
